version: '3.3'

services:
  web:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./code:/data/www:ro
    - ./config/site.nginx:/etc/nginx/conf.d/default.conf:ro
    - ./logs/nginx:/var/log/nginx
    networks:
    - code-network
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: jmorille/php7-fpm
    volumes:
    - ./code:/data/www:ro
    networks:
    - code-network

networks:
  code-network: