version: '3.3'

services:
  web:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./code:/data/www:ro
    - ./config/site.nginx:/etc/nginx/conf.d/default.conf:ro
    - ./logs/nginx:/var/log/nginx
    networks:
    - code-network
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: jmorille/php7-fpm
    volumes:
    - ./code:/data/www:ro
    networks:
    - code-network

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: webmail
      MYSQL_ROOT_PASSWORD: admin
    networks:
    - code-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    volumes:
      - ./config/phpmyadmin/theme/fallen:/www/themes/pmahomme:ro
    environment:
      PMA_HOST: db
    ports:
    - 8080:80
    networks:
    - code-network

networks:
  code-network: